### ISSUE TITLE
End Game Screens

### ISSUE THREAD

**Issue by LixinWang** [LixinWang/tennischamps#25]
Training mode: “Nice shot! Accuracy: ___”

Game mode:
“You win tennis champ! Score: ___”

“You lose :( Score: ____. Need more practice? Try training mode!”

**Comment by Yili0616** [comment]
--Design a screen for You win/ You lose with Figma. 
--After swiping, it goes to one of the screen

**Comment by Yili0616** [comment]
Okay for training. Need to revisit when getting real data from db.
