### ISSUE TITLE
Fix Navigation/ Back Button

### ISSUE THREAD

**Issue by LixinWang** [LixinWang/tennischamps#31]
For some reason the back button leads back to the splash screen for all pages. I think it's probably because we have all the navigation in one file or something. -Lixin

**Comment by mck1117** [comment]
I think we need a StackNavigator.  I'm not sure if there's a pre-cooked way to have a stacknavigator that also has a drawer.  Might work best to switch to a stacknavigator, then custom-roll a drawer component.
